# -*- coding: utf-8 -*-
"""技术报告 docx 程序化生成器（docs/技术报告.md → docs/技术报告.docx）。

纪律（系列方法论阶段 8）：md 先定稿再生成；docx 是产物，禁止手改——改动一律改
md 后重跑本脚本，并同步更新 scripts/binary_whitelist.txt 中该文件的 sha256 与
data/README.md 台账。结构守门测试（tests/test_desensitize_audit.py）校验产物
docProps 里带本脚本标记。

用法：``py -X utf8 scripts/make_report_docx.py``（需 report extras：python-docx）。
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MD_PATH = REPO_ROOT / "docs" / "技术报告.md"
DOCX_PATH = REPO_ROOT / "docs" / "技术报告.docx"
GENERATOR_MARK = "generated by scripts/make_report_docx.py"


def _add_runs(paragraph, text):
    """**bold** 与行内反引号码段的极简处理：bold 双星切分；码段原样保留。"""
    text = re.sub(r"`([^`]+)`", r"\1", text)
    for i, part in enumerate(re.split(r"\*\*", text)):
        if not part:
            continue
        run = paragraph.add_run(part)
        run.bold = i % 2 == 1


def _add_table(doc, rows):
    cells = [[c.strip() for c in r.strip().strip("|").split("|")] for r in rows]
    cells = [r for r in cells if not all(set(c) <= set("-: ") for c in r)]  # 去分隔行
    if not cells:
        return
    table = doc.add_table(rows=len(cells), cols=len(cells[0]))
    table.style = "Table Grid"
    for r, row in enumerate(cells):
        for c, val in enumerate(row):
            if c < len(table.rows[r].cells):
                table.rows[r].cells[c].text = val


def build_doc(md_text):
    """极简 md 子集转换：标题/引用/列表/表格/代码块/段落（报告 md 按此子集书写）。"""
    from docx import Document
    from docx.shared import Pt

    doc = Document()
    doc.core_properties.author = "resume-talent-pool"
    doc.core_properties.comments = GENERATOR_MARK
    lines = md_text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("```"):
            i += 1
            while i < len(lines) and not lines[i].startswith("```"):
                p = doc.add_paragraph()
                run = p.add_run(lines[i])
                run.font.name = "Consolas"
                run.font.size = Pt(9)
                i += 1
            i += 1
            continue
        if line.startswith("|"):
            rows = []
            while i < len(lines) and lines[i].startswith("|"):
                rows.append(lines[i])
                i += 1
            _add_table(doc, rows)
            continue
        if line.startswith("# "):
            doc.add_heading(line[2:].strip(), level=0)
        elif line.startswith("## "):
            doc.add_heading(line[3:].strip(), level=1)
        elif line.startswith("### "):
            doc.add_heading(line[4:].strip(), level=2)
        elif line.startswith("> "):
            p = doc.add_paragraph()
            _add_runs(p, line[2:].strip())
            for r in p.runs:
                r.italic = True
        elif re.match(r"^\d+\. ", line):
            p = doc.add_paragraph(style="List Number")
            _add_runs(p, re.sub(r"^\d+\. ", "", line))
        elif line.startswith("- "):
            p = doc.add_paragraph(style="List Bullet")
            _add_runs(p, line[2:])
        elif line.strip():
            p = doc.add_paragraph()
            _add_runs(p, line.strip())
        i += 1
    return doc


def main():
    try:
        from docx import Document  # noqa: F401  report extras 可用性检查
    except ImportError:
        print("需要 report extras：pip install -e \".[report]\"")
        return 2
    md_text = MD_PATH.read_text(encoding="utf-8")
    doc = build_doc(md_text)
    doc.save(str(DOCX_PATH))
    import hashlib

    digest = hashlib.sha256(DOCX_PATH.read_bytes()).hexdigest()
    print("written: %s (sha256 %s)" % (DOCX_PATH.name, digest[:12] + "..."))
    print("提醒：更新 scripts/binary_whitelist.txt 与 data/README.md 台账")
    return 0


if __name__ == "__main__":
    sys.exit(main())
